LIBRARY/config/routes.rb
Rails.application.routes.draw do
  get "books/index"
  get "book/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

LIBRARY/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

LIBRARY/app/models/book.rb
class Book < ApplicationRecord
end

LIBRARY/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

LIBRARY/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
   

    if @book.save
      redirect_to @book
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
    @book.destroy
    redirect_to books_path
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.expect(book: [ :title, :description ])
    end
end

LIBRARY/app/helpers/application_helper.rb
module ApplicationHelper
end

LIBRARY/app/helpers/book_helper.rb
module BookHelper
end

LIBRARY/app/helpers/books_helper.rb
module BooksHelper
end

LIBRARY/app/helpers/index_helper.rb
module IndexHelper
end

LIBRARY/app/views/books/_form.html.erb
<%= stylesheet_link_tag "application.css" %>
<div class="add-book">
<%= form_with model: book do |form| %>
  <div class="title">
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div class="description">
  <%= form.label :description, required: true %><br>
  <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

LIBRARY/app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render "form", book: @book %>
<%= link_to "Cancel", @book %>

LIBRARY/app/views/books/index.html.erb
<%= stylesheet_link_tag "application.css" %>
<h1>Books</h1>

<%= link_to "Add a New Book", new_book_path %>

<div id="books">
  <% @books.each do |book| %>
    <div>
       <%= link_to book.title, book %>
    </div>
  <% end %>
</div>

LIBRARY/app/views/books/new.html.erb
<h1>New book</h1>


<%= render "form", book: @book %>
<%= link_to "Cancel", books_path %>

LIBRARY/app/views/books/show.html.erb
<h1><%= @book.title %></h1>
<p><strong>Description:</strong> <%= @book.description %></p>

<%= link_to "Back", books_path %>
<%= link_to "Edit", edit_book_path(@book) %>
<%= button_to "Delete", @book, method: :delete, data: { turbo_confirm: "Are you sure?" } %>

LIBRARY/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Library" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>